Test cylc reinstall spots when rose-suite.conf has changed
cylc/cylc-rose pull request #178
Opened 2022-09-08 15:32 UTC by wxtim

These changes contain a test for the issue described in https://github.com/cylc/cylc-flow/pull/5125

## Requirements check-list

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to `setup.cfg`.
- [x] Is a test
- [x] No change log entry required - is a test
- [x] No documentation update required.

2022-09-12 12:34 UTC, oliver-sanders approved these changes
Confirmed test fails when run with `cylc-flow:master` but passes on your branch.

2022-09-13 12:09 UTC, datamel approved these changes

2022-09-14 10:23 UTC, oliver-sanders commented
(no need to merge into 1.1.1, get tests to pass in CI before merging)

2022-10-04 09:21 UTC, oliver-sanders commented
Test now appears to be failing on https://github.com/cylc/cylc-flow/pull/5125

Possibly something to do with the branch change from master to 8.0.x?

2022-10-05 12:24 UTC, oliver-sanders approved these changes

2022-10-06 09:13 UTC, oliver-sanders requested changes
The reason this test is failing is because change you require has not yet been merged to master - 
https://github.com/cylc/cylc-flow/pull/5178

The "fix test" commit defeats the purpose of the test?

2022-10-06 12:03 UTC, wxtim commented on tests/functional/test_reinstall.py
> +    expect = sorted(['send flow.cylc'])
```suggestion
    expect = sorted(['send rose-suite.conf', 'send flow.cylc'])
```

2022-10-06 12:04 UTC, wxtim commented
> The reason this test is failing is because change you require has not yet been merged to master - [cylc/cylc-flow#5178](https://github.com/cylc/cylc-flow/pull/5178)
> 
> The "fix test" commit defeats the purpose of the test?

Oh dear, I'm not looking very clever with all this multiple branch stuff. 🙄

2022-10-11 10:47 UTC, oliver-sanders approved these changes
Confirmed this passes after the cylc-flow fix but fails before it.

2022-10-11 10:48 UTC, merged