give Cylc install the correct options
cylc/cylc-rose pull request #52
Opened 2021-03-29 15:34 UTC by wxtim

2021-03-29 15:41 UTC, oliver-sanders commented on cylc/rose/stem.py
> +    cylc_install(parser, opts)
Ah yes, that would have been https://github.com/cylc/cylc-flow/pull/4132

2021-03-29 15:43 UTC, oliver-sanders commented
The three pre_configure tests still seem to be failing:

FAILED tests/functional/test_pre_configure.py::test_validate[06_jinja2_thorough-envvars5-None]
482
FAILED tests/functional/test_pre_configure.py::test_validate[09_template_vars_vanilla-envvars7-None]
483
FAILED tests/functional/test_pre_configure.py::test_process[06_jinja2_thorough-envvars4-None]

2021-03-29 16:41 UTC, wxtim commented
I'm not totally happy about the fix, but I think that it is sufficient.

2021-03-30 09:31 UTC, oliver-sanders approved these changes
Not too sure what's going on with the whitespace but happy tests are passing.

2021-03-30 09:35 UTC, oliver-sanders requested changes
Sorry, just spotted something.

The `REG` argument in `rose stem [REG]` is now totally ignored (it was ignored by `cylc install` anyhoo). Should remove it, the `--flow-name` argument fills this function now?

2021-03-30 10:56 UTC, datamel reviewed
I have read code and run tests, all passing for me locally. 

This is coming from your master branch btw :)

2021-03-30 13:18 UTC, wxtim commented
> This is coming from your master branch btw :)

Ooops. Ah Well

2021-03-30 14:01 UTC, oliver-sanders commented
> This is coming from your master branch btw :)

That's alright, master is just another branch.

2021-03-30 14:04 UTC, wxtim commented
> Sorry, just spotted something.
> 
> The `REG` argument in `rose stem [REG]` is now totally ignored (it was ignored by `cylc install` anyhoo). Should remove it, the `--flow-name` argument fills this function now?

Where did you spot it - I can only see it in the help docs...

2021-03-30 14:33 UTC, oliver-sanders commented on cylc/rose/stem.py
> +To run a rose-stem suite use ``cylc play``.
This isn't RST:

```suggestion
Provide a wrapper around "cylc install" for rose-stem suites.

To run a rose-stem suite use "cylc play".
```

2021-03-30 14:38 UTC, merged